# Generated by Django 5.2.10 on 2026-01-16 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0002_like_is_active_like_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='is_active',
        ),
    ]
